# Generated by Django 5.1.2 on 2024-11-07 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('file_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('file_name', models.CharField(default=None, max_length=200)),
                ('input_path', models.CharField(default=None, max_length=200)),
                ('output_path', models.CharField(default=None, max_length=200, null=True)),
                ('status', models.CharField(default=None, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updtated_at', models.DateTimeField(auto_now=True)),
                ('page_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'file_data',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=None, max_length=100)),
                ('input_path', models.CharField(default=None, max_length=200)),
                ('output_path', models.CharField(default=None, max_length=200, null=True)),
                ('status', models.CharField(default=None, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('file_id', models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='file_api.filedata')),
                ('condition', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'conditions',
            },
        ),
    ]
