# Generated by Django 5.1.2 on 2024-11-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='input_path',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='output_path',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
