# Generated by Django 5.1.2 on 2024-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0002_remove_uploadedfile_file_uploadedfile_input_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='input_path',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='output_path',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
