# Generated by Django 5.1.2 on 2024-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
