# Generated by Django 5.1.2 on 2024-11-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0003_alter_uploadedfile_input_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
