# Generated by Django 5.1.2 on 2024-11-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0004_delete_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=1000, null=True)),
                ('file_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='file_api.filedata')),
            ],
            options={
                'db_table': 'conditions',
            },
        ),
    ]
