# Generated by Django 5.1.2 on 2024-11-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0005_fileconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
