# Generated by Django 5.1.2 on 2024-11-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0007_alter_filedata_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileconditions',
            name='file_id',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='file_api.filedata'),
        ),
    ]
