# Generated by Django 5.1.2 on 2024-11-08 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0009_alter_filedata_input_path_alter_filedata_output_path'),
        ('user_api', '0002_alter_usercredentials_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.projects'),
        ),
    ]
