# Generated by Django 5.1.2 on 2024-11-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usercredentials',
            managers=[
            ],
        ),
    ]
